server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/phoneshop_night
    username: account
    password: account123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: false

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
